# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Interblag
tagline:          'Ride the Walrus!'
description:      'A blog about Security, Free Software, and General Geekiness'
url:              https://dioberne.github.io/
baseurl:          /


paginate:         5

# Custom vars
version:          ff02::2

github:
  repo:           https://github.com/Dioberne/dioberne.github.io
